### ISSUE TITLE
Todo list for a 0.1-0 release to CRAN

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/coenocliner#5]
These are the things we need to do before a 0.1-0 release should be made and the package sent to CRAN:
- [x] `Beta()` and `Gaussian()` should be rewritten to take arguments `x` and `y` plus two lists `px` and `py` containing the parameters for `m` species each on gradients `x` and `y`. See #6 
- [x] Clean up the package to remove the old `sim1dPoisson()`, `sim2dNegbin()` functions, plus remove the `gaussianResponse()`, `biGaussianResponse()`, and `betaResponse()` functions. See #7.
- [x] Tidy the existing Rd (in roxygen notation) ready for a first release. See #8.
- [x] Write documentation for `Gaussian()` and `Beta()` and export these functions in the namespace. See #9.
- [x] Fill out the unit tests to cover the main functionality and use cases. See #10.
- [X] Add a `inst/ChangeLog` file. See #13.
- [x] Add a `inst/NEWS.Rd` file. See #11.
- [x] Add a `man/coenocliner-package.Rd` file. See #12.
- [x] Add a `inst/CITATION` file to contain the recommended citation. See #14.
- [x] Implement `Beta()` for two gradients. See #15.
